// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: worker.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle
type StatusResponse_JobStatus int32

const (
	// StatusUnspecified indicates the status is unspecified.
	StatusResponse_STATUS_UNSPECIFIED StatusResponse_JobStatus = 0
	// Running indicates the process has started and is currently active.
	StatusResponse_RUNNING StatusResponse_JobStatus = 1
	// Stopped indicates the process was manually terminated by a user request.
	StatusResponse_STOPPED StatusResponse_JobStatus = 2
	// Completed indicates the process exited on its own with a zero exit code.
	StatusResponse_COMPLETED StatusResponse_JobStatus = 3
	// Failed indicates the process exited with a non-zero exit code or system error.
	StatusResponse_FAILED StatusResponse_JobStatus = 4
)

// Enum value maps for StatusResponse_JobStatus.
var (
	StatusResponse_JobStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "RUNNING",
		2: "STOPPED",
		3: "COMPLETED",
		4: "FAILED",
	}
	StatusResponse_JobStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"RUNNING":            1,
		"STOPPED":            2,
		"COMPLETED":          3,
		"FAILED":             4,
	}
)

func (x StatusResponse_JobStatus) Enum() *StatusResponse_JobStatus {
	p := new(StatusResponse_JobStatus)
	*p = x
	return p
}

func (x StatusResponse_JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (StatusResponse_JobStatus) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x StatusResponse_JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_JobStatus.Descriptor instead.
func (StatusResponse_JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6, 0}
}

// Distinguishes between output streams
type LogChunk_Source int32

const (
	// Zero value is reserved for "not specified" to avoid ambiguity
	LogChunk_SOURCE_UNSPECIFIED LogChunk_Source = 0
	LogChunk_STDOUT             LogChunk_Source = 1
	LogChunk_STDERR             LogChunk_Source = 2
)

// Enum value maps for LogChunk_Source.
var (
	LogChunk_Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "STDOUT",
		2: "STDERR",
	}
	LogChunk_Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"STDOUT":             1,
		"STDERR":             2,
	}
)

func (x LogChunk_Source) Enum() *LogChunk_Source {
	p := new(LogChunk_Source)
	*p = x
	return p
}

func (x LogChunk_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogChunk_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[1].Descriptor()
}

func (LogChunk_Source) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[1]
}

func (x LogChunk_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogChunk_Source.Descriptor instead.
func (LogChunk_Source) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8, 0}
}

type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command is the path to the executable to be run.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Args is the list of arguments to be passed to the executable.
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// WorkingDirectory is the path where the process will execute.
	WorkingDirectory string `protobuf:"bytes,3,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StartRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JobID is the unique identifier for the started job.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Status indicates the initial state of the job (usually RUNNING).
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// CreatedAt is the timestamp when the job was successfully initiated.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type StopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JobID is the unique identifier of the job to stop.
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message provides a human-readable result of the stop operation.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JobID is the unique identifier of the job to query.
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Resource limits to be enforced via Cgroups v2
type ResourceLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MemoryBytes is the maximum physical memory the process tree can consume.
	MemoryBytes uint64 `protobuf:"varint,1,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// CPUPercent is the maximum CPU usage allowed (e.g., 0.5 for 50% of a core).
	CpuPercent float64 `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	// DiskReadBPS is the maximum read throughput in bytes per second.
	DiskReadBps uint32 `protobuf:"varint,3,opt,name=disk_read_bps,json=diskReadBps,proto3" json:"disk_read_bps,omitempty"`
	// DiskWriteBPS is the maximum write throughput in bytes per second.
	DiskWriteBps  uint32 `protobuf:"varint,4,opt,name=disk_write_bps,json=diskWriteBps,proto3" json:"disk_write_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceLimits) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceLimits) GetDiskReadBps() uint32 {
	if x != nil {
		return x.DiskReadBps
	}
	return 0
}

func (x *ResourceLimits) GetDiskWriteBps() uint32 {
	if x != nil {
		return x.DiskWriteBps
	}
	return 0
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JobID is the unique identifier for the job.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Owner is the Common Name (CN) of the client who started the job.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Command is the path to the executable.
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// Args is the list of arguments passed to the executable.
	Args []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	// Status is the current machine-state of the job.
	Status StatusResponse_JobStatus `protobuf:"varint,5,opt,name=status,proto3,enum=worker.StatusResponse_JobStatus" json:"status,omitempty"`
	// StartedAt is the timestamp when the process started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// EndedAt is the timestamp when the process ended (if applicable).
	EndedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	// ExitCode is the exit code returned by the process upon termination.
	ExitCode int32 `protobuf:"varint,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Limits defines the resource boundaries applied to the job.
	Limits        *ResourceLimits `protobuf:"bytes,9,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StatusResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *StatusResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StatusResponse) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StatusResponse) GetStatus() StatusResponse_JobStatus {
	if x != nil {
		return x.Status
	}
	return StatusResponse_STATUS_UNSPECIFIED
}

func (x *StatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StatusResponse) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *StatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StatusResponse) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JobID is the unique identifier of the job to stream logs from.
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *StreamRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data contains the raw bytes from the process output.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Source indicates whether the data came from stdout or stderr.
	Source LogChunk_Source `protobuf:"varint,2,opt,name=source,proto3,enum=worker.LogChunk_Source" json:"source,omitempty"`
	// Timestamp is the time when the output was captured.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetSource() LogChunk_Source {
	if x != nil {
		return x.Source
	}
	return LogChunk_SOURCE_UNSPECIFIED
}

func (x *LogChunk) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x06worker\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\fStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12+\n" +
	"\x11working_directory\x18\x03 \x01(\tR\x10workingDirectory\"y\n" +
	"\rStartResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"$\n" +
	"\vStopRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\rStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9e\x01\n" +
	"\x0eResourceLimits\x12!\n" +
	"\fmemory_bytes\x18\x01 \x01(\x04R\vmemoryBytes\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12\"\n" +
	"\rdisk_read_bps\x18\x03 \x01(\rR\vdiskReadBps\x12$\n" +
	"\x0edisk_write_bps\x18\x04 \x01(\rR\fdiskWriteBps\"\xd0\x03\n" +
	"\x0eStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2 .worker.StatusResponse.JobStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bended_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendedAt\x88\x01\x01\x12\x1b\n" +
	"\texit_code\x18\b \x01(\x05R\bexitCode\x12.\n" +
	"\x06limits\x18\t \x01(\v2\x16.worker.ResourceLimitsR\x06limits\"X\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aSTOPPED\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04B\v\n" +
	"\t_ended_at\"&\n" +
	"\rStreamRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xc3\x01\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12/\n" +
	"\x06source\x18\x02 \x01(\x0e2\x17.worker.LogChunk.SourceR\x06source\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"8\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x022\xe2\x01\n" +
	"\tJobWorker\x124\n" +
	"\x05Start\x12\x14.worker.StartRequest\x1a\x15.worker.StartResponse\x121\n" +
	"\x04Stop\x12\x13.worker.StopRequest\x1a\x14.worker.StopResponse\x127\n" +
	"\x06Status\x12\x15.worker.StatusRequest\x1a\x16.worker.StatusResponse\x123\n" +
	"\x06Stream\x12\x15.worker.StreamRequest\x1a\x10.worker.LogChunk0\x01B$Z\"github.com/teleport-handson/api/v1b\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_worker_proto_goTypes = []any{
	(StatusResponse_JobStatus)(0), // 0: worker.StatusResponse.JobStatus
	(LogChunk_Source)(0),          // 1: worker.LogChunk.Source
	(*StartRequest)(nil),          // 2: worker.StartRequest
	(*StartResponse)(nil),         // 3: worker.StartResponse
	(*StopRequest)(nil),           // 4: worker.StopRequest
	(*StopResponse)(nil),          // 5: worker.StopResponse
	(*StatusRequest)(nil),         // 6: worker.StatusRequest
	(*ResourceLimits)(nil),        // 7: worker.ResourceLimits
	(*StatusResponse)(nil),        // 8: worker.StatusResponse
	(*StreamRequest)(nil),         // 9: worker.StreamRequest
	(*LogChunk)(nil),              // 10: worker.LogChunk
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_worker_proto_depIdxs = []int32{
	11, // 0: worker.StartResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: worker.StatusResponse.status:type_name -> worker.StatusResponse.JobStatus
	11, // 2: worker.StatusResponse.started_at:type_name -> google.protobuf.Timestamp
	11, // 3: worker.StatusResponse.ended_at:type_name -> google.protobuf.Timestamp
	7,  // 4: worker.StatusResponse.limits:type_name -> worker.ResourceLimits
	1,  // 5: worker.LogChunk.source:type_name -> worker.LogChunk.Source
	11, // 6: worker.LogChunk.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 7: worker.JobWorker.Start:input_type -> worker.StartRequest
	4,  // 8: worker.JobWorker.Stop:input_type -> worker.StopRequest
	6,  // 9: worker.JobWorker.Status:input_type -> worker.StatusRequest
	9,  // 10: worker.JobWorker.Stream:input_type -> worker.StreamRequest
	3,  // 11: worker.JobWorker.Start:output_type -> worker.StartResponse
	5,  // 12: worker.JobWorker.Stop:output_type -> worker.StopResponse
	8,  // 13: worker.JobWorker.Status:output_type -> worker.StatusResponse
	10, // 14: worker.JobWorker.Stream:output_type -> worker.LogChunk
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
