// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jobworker/v1/service.proto

package jobworkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobState indicates the current state of a job.
type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0 // Invalid state
	JobState_JOB_STATE_RUNNING     JobState = 1 // Process is currently executing
	JobState_JOB_STATE_COMPLETED   JobState = 2 // Process exited on its own
	JobState_JOB_STATE_STOPPING    JobState = 3 // StopJob called, waiting on exit
	JobState_JOB_STATE_STOPPED     JobState = 4 // Terminated by user via StopJob
	JobState_JOB_STATE_KILLED      JobState = 5 // Killed by signal (e.g., OOM) without StopJob
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_RUNNING",
		2: "JOB_STATE_COMPLETED",
		3: "JOB_STATE_STOPPING",
		4: "JOB_STATE_STOPPED",
		5: "JOB_STATE_KILLED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_RUNNING":     1,
		"JOB_STATE_COMPLETED":   2,
		"JOB_STATE_STOPPING":    3,
		"JOB_STATE_STOPPED":     4,
		"JOB_STATE_KILLED":      5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_jobworker_v1_service_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_jobworker_v1_service_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{0}
}

// ResourceLimits specifies cgroups v2 resource constraints.
// All fields are optional; zero values mean no limit.
type ResourceLimits struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuMax         float64                `protobuf:"fixed64,1,opt,name=cpu_max,json=cpuMax,proto3" json:"cpu_max,omitempty"`                          // Fraction of CPU (0.5 = half core, 2.0 = two cores)
	MemoryMaxBytes int64                  `protobuf:"varint,2,opt,name=memory_max_bytes,json=memoryMaxBytes,proto3" json:"memory_max_bytes,omitempty"` // Memory limit in bytes
	IoMaxReadBps   int64                  `protobuf:"varint,3,opt,name=io_max_read_bps,json=ioMaxReadBps,proto3" json:"io_max_read_bps,omitempty"`     // Max read throughput in bytes/sec
	IoMaxWriteBps  int64                  `protobuf:"varint,4,opt,name=io_max_write_bps,json=ioMaxWriteBps,proto3" json:"io_max_write_bps,omitempty"`  // Max write throughput in bytes/sec
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_jobworker_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimits) GetCpuMax() float64 {
	if x != nil {
		return x.CpuMax
	}
	return 0
}

func (x *ResourceLimits) GetMemoryMaxBytes() int64 {
	if x != nil {
		return x.MemoryMaxBytes
	}
	return 0
}

func (x *ResourceLimits) GetIoMaxReadBps() int64 {
	if x != nil {
		return x.IoMaxReadBps
	}
	return 0
}

func (x *ResourceLimits) GetIoMaxWriteBps() int64 {
	if x != nil {
		return x.IoMaxWriteBps
	}
	return 0
}

// StartJobRequest specifies a process to execute.
type StartJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // Path to executable (required)
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`       // Command-line arguments
	Limits        *ResourceLimits        `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`   // Resource limits (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_jobworker_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartJobRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StartJobRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // Unique identifier for the created job
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_jobworker_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *StartJobResponse) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type StopJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobRequest) Reset() {
	*x = StopJobRequest{}
	mi := &file_jobworker_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobRequest) ProtoMessage() {}

func (x *StopJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobRequest.ProtoReflect.Descriptor instead.
func (*StopJobRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *StopJobRequest) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type StopJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobResponse) Reset() {
	*x = StopJobResponse{}
	mi := &file_jobworker_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobResponse) ProtoMessage() {}

func (x *StopJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobResponse.ProtoReflect.Descriptor instead.
func (*StopJobResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{4}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_jobworker_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusRequest) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

// GetStatusResponse returns the current state of a job.
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=jobworker.v1.JobState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // Exit code (only valid if state != RUNNING)
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_jobworker_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusResponse) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetStatusResponse) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *GetStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *GetStatusResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetStatusResponse) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"` // If true, stream waits for new output until job exits
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_jobworker_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetLogsRequest) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

// GetLogsResponse contains a chunk of output data.
// Output is opaque binary data with no encoding assumptions.
type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_jobworker_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetLogsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_jobworker_v1_service_proto protoreflect.FileDescriptor

const file_jobworker_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1ajobworker/v1/service.proto\x12\fjobworker.v1\"\xa3\x01\n" +
	"\x0eResourceLimits\x12\x17\n" +
	"\acpu_max\x18\x01 \x01(\x01R\x06cpuMax\x12(\n" +
	"\x10memory_max_bytes\x18\x02 \x01(\x03R\x0ememoryMaxBytes\x12%\n" +
	"\x0fio_max_read_bps\x18\x03 \x01(\x03R\fioMaxReadBps\x12'\n" +
	"\x10io_max_write_bps\x18\x04 \x01(\x03R\rioMaxWriteBps\"u\n" +
	"\x0fStartJobRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x124\n" +
	"\x06limits\x18\x03 \x01(\v2\x1c.jobworker.v1.ResourceLimitsR\x06limits\")\n" +
	"\x10StartJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"'\n" +
	"\x0eStopJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"\x11\n" +
	"\x0fStopJobResponse\")\n" +
	"\x10GetStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"\xa3\x01\n" +
	"\x11GetStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.jobworker.v1.JobStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\"?\n" +
	"\x0eGetLogsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"%\n" +
	"\x0fGetLogsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*\x9a\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x01\x12\x17\n" +
	"\x13JOB_STATE_COMPLETED\x10\x02\x12\x16\n" +
	"\x12JOB_STATE_STOPPING\x10\x03\x12\x15\n" +
	"\x11JOB_STATE_STOPPED\x10\x04\x12\x14\n" +
	"\x10JOB_STATE_KILLED\x10\x052\xbd\x02\n" +
	"\x10JobWorkerService\x12I\n" +
	"\bStartJob\x12\x1d.jobworker.v1.StartJobRequest\x1a\x1e.jobworker.v1.StartJobResponse\x12F\n" +
	"\aStopJob\x12\x1c.jobworker.v1.StopJobRequest\x1a\x1d.jobworker.v1.StopJobResponse\x12L\n" +
	"\tGetStatus\x12\x1e.jobworker.v1.GetStatusRequest\x1a\x1f.jobworker.v1.GetStatusResponse\x12H\n" +
	"\aGetLogs\x12\x1c.jobworker.v1.GetLogsRequest\x1a\x1d.jobworker.v1.GetLogsResponse0\x01B\xb9\x01\n" +
	"\x10com.jobworker.v1B\fServiceProtoP\x01ZFgithub.com/benmoss/job-worker-service/pkg/api/jobworker/v1;jobworkerv1\xa2\x02\x03JXX\xaa\x02\fJobworker.V1\xca\x02\fJobworker\\V1\xe2\x02\x18Jobworker\\V1\\GPBMetadata\xea\x02\rJobworker::V1b\x06proto3"

var (
	file_jobworker_v1_service_proto_rawDescOnce sync.Once
	file_jobworker_v1_service_proto_rawDescData []byte
)

func file_jobworker_v1_service_proto_rawDescGZIP() []byte {
	file_jobworker_v1_service_proto_rawDescOnce.Do(func() {
		file_jobworker_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobworker_v1_service_proto_rawDesc), len(file_jobworker_v1_service_proto_rawDesc)))
	})
	return file_jobworker_v1_service_proto_rawDescData
}

var file_jobworker_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobworker_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_jobworker_v1_service_proto_goTypes = []any{
	(JobState)(0),             // 0: jobworker.v1.JobState
	(*ResourceLimits)(nil),    // 1: jobworker.v1.ResourceLimits
	(*StartJobRequest)(nil),   // 2: jobworker.v1.StartJobRequest
	(*StartJobResponse)(nil),  // 3: jobworker.v1.StartJobResponse
	(*StopJobRequest)(nil),    // 4: jobworker.v1.StopJobRequest
	(*StopJobResponse)(nil),   // 5: jobworker.v1.StopJobResponse
	(*GetStatusRequest)(nil),  // 6: jobworker.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 7: jobworker.v1.GetStatusResponse
	(*GetLogsRequest)(nil),    // 8: jobworker.v1.GetLogsRequest
	(*GetLogsResponse)(nil),   // 9: jobworker.v1.GetLogsResponse
}
var file_jobworker_v1_service_proto_depIdxs = []int32{
	1, // 0: jobworker.v1.StartJobRequest.limits:type_name -> jobworker.v1.ResourceLimits
	0, // 1: jobworker.v1.GetStatusResponse.state:type_name -> jobworker.v1.JobState
	2, // 2: jobworker.v1.JobWorkerService.StartJob:input_type -> jobworker.v1.StartJobRequest
	4, // 3: jobworker.v1.JobWorkerService.StopJob:input_type -> jobworker.v1.StopJobRequest
	6, // 4: jobworker.v1.JobWorkerService.GetStatus:input_type -> jobworker.v1.GetStatusRequest
	8, // 5: jobworker.v1.JobWorkerService.GetLogs:input_type -> jobworker.v1.GetLogsRequest
	3, // 6: jobworker.v1.JobWorkerService.StartJob:output_type -> jobworker.v1.StartJobResponse
	5, // 7: jobworker.v1.JobWorkerService.StopJob:output_type -> jobworker.v1.StopJobResponse
	7, // 8: jobworker.v1.JobWorkerService.GetStatus:output_type -> jobworker.v1.GetStatusResponse
	9, // 9: jobworker.v1.JobWorkerService.GetLogs:output_type -> jobworker.v1.GetLogsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jobworker_v1_service_proto_init() }
func file_jobworker_v1_service_proto_init() {
	if File_jobworker_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobworker_v1_service_proto_rawDesc), len(file_jobworker_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobworker_v1_service_proto_goTypes,
		DependencyIndexes: file_jobworker_v1_service_proto_depIdxs,
		EnumInfos:         file_jobworker_v1_service_proto_enumTypes,
		MessageInfos:      file_jobworker_v1_service_proto_msgTypes,
	}.Build()
	File_jobworker_v1_service_proto = out.File
	file_jobworker_v1_service_proto_goTypes = nil
	file_jobworker_v1_service_proto_depIdxs = nil
}
