// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: jobworker/v1/service.proto

package jobworkerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobWorkerService_StartJob_FullMethodName  = "/jobworker.v1.JobWorkerService/StartJob"
	JobWorkerService_StopJob_FullMethodName   = "/jobworker.v1.JobWorkerService/StopJob"
	JobWorkerService_GetStatus_FullMethodName = "/jobworker.v1.JobWorkerService/GetStatus"
	JobWorkerService_GetLogs_FullMethodName   = "/jobworker.v1.JobWorkerService/GetLogs"
)

// JobWorkerServiceClient is the client API for JobWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobWorkerService manages Linux processes with resource constraints.
type JobWorkerServiceClient interface {
	// StartJob creates and executes a new job. Returns after the process starts.
	// Errors: INVALID_ARGUMENT (empty command), PERMISSION_DENIED
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	// StopJob terminates a job and all its child processes.
	// Errors: NOT_FOUND, PERMISSION_DENIED
	StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*StopJobResponse, error)
	// GetStatus returns the current state of a job.
	// Errors: NOT_FOUND, PERMISSION_DENIED
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// GetLogs streams the job's combined stdout/stderr from the beginning.
	// If follow=true, the stream continues until the job exits.
	// If follow=false, returns current output and closes.
	// Errors: NOT_FOUND, PERMISSION_DENIED
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetLogsResponse], error)
}

type jobWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobWorkerServiceClient(cc grpc.ClientConnInterface) JobWorkerServiceClient {
	return &jobWorkerServiceClient{cc}
}

func (c *jobWorkerServiceClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, JobWorkerService_StartJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobWorkerServiceClient) StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*StopJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopJobResponse)
	err := c.cc.Invoke(ctx, JobWorkerService_StopJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobWorkerServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, JobWorkerService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobWorkerServiceClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobWorkerService_ServiceDesc.Streams[0], JobWorkerService_GetLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLogsRequest, GetLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobWorkerService_GetLogsClient = grpc.ServerStreamingClient[GetLogsResponse]

// JobWorkerServiceServer is the server API for JobWorkerService service.
// All implementations must embed UnimplementedJobWorkerServiceServer
// for forward compatibility.
//
// JobWorkerService manages Linux processes with resource constraints.
type JobWorkerServiceServer interface {
	// StartJob creates and executes a new job. Returns after the process starts.
	// Errors: INVALID_ARGUMENT (empty command), PERMISSION_DENIED
	StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error)
	// StopJob terminates a job and all its child processes.
	// Errors: NOT_FOUND, PERMISSION_DENIED
	StopJob(context.Context, *StopJobRequest) (*StopJobResponse, error)
	// GetStatus returns the current state of a job.
	// Errors: NOT_FOUND, PERMISSION_DENIED
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// GetLogs streams the job's combined stdout/stderr from the beginning.
	// If follow=true, the stream continues until the job exits.
	// If follow=false, returns current output and closes.
	// Errors: NOT_FOUND, PERMISSION_DENIED
	GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[GetLogsResponse]) error
	mustEmbedUnimplementedJobWorkerServiceServer()
}

// UnimplementedJobWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobWorkerServiceServer struct{}

func (UnimplementedJobWorkerServiceServer) StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedJobWorkerServiceServer) StopJob(context.Context, *StopJobRequest) (*StopJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopJob not implemented")
}
func (UnimplementedJobWorkerServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedJobWorkerServiceServer) GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[GetLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedJobWorkerServiceServer) mustEmbedUnimplementedJobWorkerServiceServer() {}
func (UnimplementedJobWorkerServiceServer) testEmbeddedByValue()                          {}

// UnsafeJobWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobWorkerServiceServer will
// result in compilation errors.
type UnsafeJobWorkerServiceServer interface {
	mustEmbedUnimplementedJobWorkerServiceServer()
}

func RegisterJobWorkerServiceServer(s grpc.ServiceRegistrar, srv JobWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedJobWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobWorkerService_ServiceDesc, srv)
}

func _JobWorkerService_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServiceServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobWorkerService_StartJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServiceServer).StartJob(ctx, req.(*StartJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobWorkerService_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServiceServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobWorkerService_StopJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServiceServer).StopJob(ctx, req.(*StopJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobWorkerService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobWorkerService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobWorkerService_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobWorkerServiceServer).GetLogs(m, &grpc.GenericServerStream[GetLogsRequest, GetLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobWorkerService_GetLogsServer = grpc.ServerStreamingServer[GetLogsResponse]

// JobWorkerService_ServiceDesc is the grpc.ServiceDesc for JobWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobworker.v1.JobWorkerService",
	HandlerType: (*JobWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJob",
			Handler:    _JobWorkerService_StartJob_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _JobWorkerService_StopJob_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _JobWorkerService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogs",
			Handler:       _JobWorkerService_GetLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jobworker/v1/service.proto",
}
