// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStartStatus int32

const (
	JobStartStatus_JobStartStatus_RUNNING             JobStartStatus = 0
	JobStartStatus_JobStartStatus_EXITED_INSTANTLY    JobStartStatus = 1
	JobStartStatus_JobStartStatus_INVALID_PERMISSIONS JobStartStatus = 2
	JobStartStatus_JobStartStatus_COMMAND_NOT_FOUND   JobStartStatus = 3
)

// Enum value maps for JobStartStatus.
var (
	JobStartStatus_name = map[int32]string{
		0: "JobStartStatus_RUNNING",
		1: "JobStartStatus_EXITED_INSTANTLY",
		2: "JobStartStatus_INVALID_PERMISSIONS",
		3: "JobStartStatus_COMMAND_NOT_FOUND",
	}
	JobStartStatus_value = map[string]int32{
		"JobStartStatus_RUNNING":             0,
		"JobStartStatus_EXITED_INSTANTLY":    1,
		"JobStartStatus_INVALID_PERMISSIONS": 2,
		"JobStartStatus_COMMAND_NOT_FOUND":   3,
	}
)

func (x JobStartStatus) Enum() *JobStartStatus {
	p := new(JobStartStatus)
	*p = x
	return p
}

func (x JobStartStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStartStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (JobStartStatus) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x JobStartStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStartStatus.Descriptor instead.
func (JobStartStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

// Query Response
type JobStatus int32

const (
	JobStatus_JobStatus_RUNNING     JobStatus = 0
	JobStatus_JobStatus_ENDED       JobStatus = 1
	JobStatus_JobStatus_FORCE_ENDED JobStatus = 2
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JobStatus_RUNNING",
		1: "JobStatus_ENDED",
		2: "JobStatus_FORCE_ENDED",
	}
	JobStatus_value = map[string]int32{
		"JobStatus_RUNNING":     0,
		"JobStatus_ENDED":       1,
		"JobStatus_FORCE_ENDED": 2,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

// Start Messages
type JobStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStartRequest) Reset() {
	*x = JobStartRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartRequest) ProtoMessage() {}

func (x *JobStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartRequest.ProtoReflect.Descriptor instead.
func (*JobStartRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *JobStartRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type JobStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Status        JobStartStatus         `protobuf:"varint,2,opt,name=Status,proto3,enum=JobStartStatus" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStartResponse) Reset() {
	*x = JobStartResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartResponse) ProtoMessage() {}

func (x *JobStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartResponse.ProtoReflect.Descriptor instead.
func (*JobStartResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *JobStartResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStartResponse) GetStatus() JobStartStatus {
	if x != nil {
		return x.Status
	}
	return JobStartStatus_JobStartStatus_RUNNING
}

// Stop/Query/Tail Request Message
type JobIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobIdRequest) Reset() {
	*x = JobIdRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobIdRequest) ProtoMessage() {}

func (x *JobIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobIdRequest.ProtoReflect.Descriptor instead.
func (*JobIdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *JobIdRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Stop Response
type JobStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStopResponse) Reset() {
	*x = JobStopResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStopResponse) ProtoMessage() {}

func (x *JobStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStopResponse.ProtoReflect.Descriptor instead.
func (*JobStopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobStatus     JobStatus              `protobuf:"varint,1,opt,name=jobStatus,proto3,enum=JobStatus" json:"jobStatus,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *JobStatusResponse) GetJobStatus() JobStatus {
	if x != nil {
		return x.JobStatus
	}
	return JobStatus_JobStatus_RUNNING
}

func (x *JobStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// Tail Message - Stream
type JobOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobOutputResponse) Reset() {
	*x = JobOutputResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOutputResponse) ProtoMessage() {}

func (x *JobOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOutputResponse.ProtoReflect.Descriptor instead.
func (*JobOutputResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *JobOutputResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\"+\n" +
	"\x0fJobStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\"Q\n" +
	"\x10JobStartResponse\x12\x14\n" +
	"\x05jobId\x18\x01 \x01(\tR\x05jobId\x12'\n" +
	"\x06Status\x18\x02 \x01(\x0e2\x0f.JobStartStatusR\x06Status\"$\n" +
	"\fJobIdRequest\x12\x14\n" +
	"\x05jobId\x18\x01 \x01(\tR\x05jobId\"\x11\n" +
	"\x0fJobStopResponse\"Y\n" +
	"\x11JobStatusResponse\x12(\n" +
	"\tjobStatus\x18\x01 \x01(\x0e2\n" +
	".JobStatusR\tjobStatus\x12\x1a\n" +
	"\bexitCode\x18\x02 \x01(\x05R\bexitCode\"-\n" +
	"\x11JobOutputResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage*\x9f\x01\n" +
	"\x0eJobStartStatus\x12\x1a\n" +
	"\x16JobStartStatus_RUNNING\x10\x00\x12#\n" +
	"\x1fJobStartStatus_EXITED_INSTANTLY\x10\x01\x12&\n" +
	"\"JobStartStatus_INVALID_PERMISSIONS\x10\x02\x12$\n" +
	" JobStartStatus_COMMAND_NOT_FOUND\x10\x03*R\n" +
	"\tJobStatus\x12\x15\n" +
	"\x11JobStatus_RUNNING\x10\x00\x12\x13\n" +
	"\x0fJobStatus_ENDED\x10\x01\x12\x19\n" +
	"\x15JobStatus_FORCE_ENDED\x10\x022\xbe\x01\n" +
	"\vJobsService\x12,\n" +
	"\x05Start\x12\x10.JobStartRequest\x1a\x11.JobStartResponse\x12'\n" +
	"\x04Stop\x12\r.JobIdRequest\x1a\x10.JobStopResponse\x12+\n" +
	"\x06Status\x12\r.JobIdRequest\x1a\x12.JobStatusResponse\x12+\n" +
	"\x04Tail\x12\r.JobIdRequest\x1a\x12.JobOutputResponse0\x01B.Z,github.com/richyhbm/teleport-challenge/protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(JobStartStatus)(0),       // 0: JobStartStatus
	(JobStatus)(0),            // 1: JobStatus
	(*JobStartRequest)(nil),   // 2: JobStartRequest
	(*JobStartResponse)(nil),  // 3: JobStartResponse
	(*JobIdRequest)(nil),      // 4: JobIdRequest
	(*JobStopResponse)(nil),   // 5: JobStopResponse
	(*JobStatusResponse)(nil), // 6: JobStatusResponse
	(*JobOutputResponse)(nil), // 7: JobOutputResponse
}
var file_api_proto_depIdxs = []int32{
	0, // 0: JobStartResponse.Status:type_name -> JobStartStatus
	1, // 1: JobStatusResponse.jobStatus:type_name -> JobStatus
	2, // 2: JobsService.Start:input_type -> JobStartRequest
	4, // 3: JobsService.Stop:input_type -> JobIdRequest
	4, // 4: JobsService.Status:input_type -> JobIdRequest
	4, // 5: JobsService.Tail:input_type -> JobIdRequest
	3, // 6: JobsService.Start:output_type -> JobStartResponse
	5, // 7: JobsService.Stop:output_type -> JobStopResponse
	6, // 8: JobsService.Status:output_type -> JobStatusResponse
	7, // 9: JobsService.Tail:output_type -> JobOutputResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
