// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jobworker/v1/jobworker.proto

package jobworkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 1
	JobStatus_JOB_STATUS_EXITED      JobStatus = 2
	JobStatus_JOB_STATUS_STOPPED     JobStatus = 3
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_RUNNING",
		2: "JOB_STATUS_EXITED",
		3: "JOB_STATUS_STOPPED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_RUNNING":     1,
		"JOB_STATUS_EXITED":      2,
		"JOB_STATUS_STOPPED":     3,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jobworker_v1_jobworker_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_jobworker_v1_jobworker_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{0}
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{3}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=jobworker.v1.JobStatus" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // Meaningful when status is EXITED or STOPPED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *GetStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type StreamOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputRequest) Reset() {
	*x = StreamOutputRequest{}
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputRequest) ProtoMessage() {}

func (x *StreamOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputRequest.ProtoReflect.Descriptor instead.
func (*StreamOutputRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{6}
}

func (x *StreamOutputRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StreamOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputResponse) Reset() {
	*x = StreamOutputResponse{}
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputResponse) ProtoMessage() {}

func (x *StreamOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_v1_jobworker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputResponse.ProtoReflect.Descriptor instead.
func (*StreamOutputResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_v1_jobworker_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOutputResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_jobworker_v1_jobworker_proto protoreflect.FileDescriptor

const file_jobworker_v1_jobworker_proto_rawDesc = "" +
	"\n" +
	"\x1cjobworker/v1/jobworker.proto\x12\fjobworker.v1\"<\n" +
	"\fStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"&\n" +
	"\rStartResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"$\n" +
	"\vStopRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x0e\n" +
	"\fStopResponse\")\n" +
	"\x10GetStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"x\n" +
	"\x11GetStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.jobworker.v1.JobStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\",\n" +
	"\x13StreamOutputRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"*\n" +
	"\x14StreamOutputResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*n\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x01\x12\x15\n" +
	"\x11JOB_STATUS_EXITED\x10\x02\x12\x16\n" +
	"\x12JOB_STATUS_STOPPED\x10\x032\xb3\x02\n" +
	"\tJobWorker\x12@\n" +
	"\x05Start\x12\x1a.jobworker.v1.StartRequest\x1a\x1b.jobworker.v1.StartResponse\x12=\n" +
	"\x04Stop\x12\x19.jobworker.v1.StopRequest\x1a\x1a.jobworker.v1.StopResponse\x12L\n" +
	"\tGetStatus\x12\x1e.jobworker.v1.GetStatusRequest\x1a\x1f.jobworker.v1.GetStatusResponse\x12W\n" +
	"\fStreamOutput\x12!.jobworker.v1.StreamOutputRequest\x1a\".jobworker.v1.StreamOutputResponse0\x01B?Z=github.com/GevorgGal/jobworker/proto/jobworker/v1;jobworkerv1b\x06proto3"

var (
	file_jobworker_v1_jobworker_proto_rawDescOnce sync.Once
	file_jobworker_v1_jobworker_proto_rawDescData []byte
)

func file_jobworker_v1_jobworker_proto_rawDescGZIP() []byte {
	file_jobworker_v1_jobworker_proto_rawDescOnce.Do(func() {
		file_jobworker_v1_jobworker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobworker_v1_jobworker_proto_rawDesc), len(file_jobworker_v1_jobworker_proto_rawDesc)))
	})
	return file_jobworker_v1_jobworker_proto_rawDescData
}

var file_jobworker_v1_jobworker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobworker_v1_jobworker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_jobworker_v1_jobworker_proto_goTypes = []any{
	(JobStatus)(0),               // 0: jobworker.v1.JobStatus
	(*StartRequest)(nil),         // 1: jobworker.v1.StartRequest
	(*StartResponse)(nil),        // 2: jobworker.v1.StartResponse
	(*StopRequest)(nil),          // 3: jobworker.v1.StopRequest
	(*StopResponse)(nil),         // 4: jobworker.v1.StopResponse
	(*GetStatusRequest)(nil),     // 5: jobworker.v1.GetStatusRequest
	(*GetStatusResponse)(nil),    // 6: jobworker.v1.GetStatusResponse
	(*StreamOutputRequest)(nil),  // 7: jobworker.v1.StreamOutputRequest
	(*StreamOutputResponse)(nil), // 8: jobworker.v1.StreamOutputResponse
}
var file_jobworker_v1_jobworker_proto_depIdxs = []int32{
	0, // 0: jobworker.v1.GetStatusResponse.status:type_name -> jobworker.v1.JobStatus
	1, // 1: jobworker.v1.JobWorker.Start:input_type -> jobworker.v1.StartRequest
	3, // 2: jobworker.v1.JobWorker.Stop:input_type -> jobworker.v1.StopRequest
	5, // 3: jobworker.v1.JobWorker.GetStatus:input_type -> jobworker.v1.GetStatusRequest
	7, // 4: jobworker.v1.JobWorker.StreamOutput:input_type -> jobworker.v1.StreamOutputRequest
	2, // 5: jobworker.v1.JobWorker.Start:output_type -> jobworker.v1.StartResponse
	4, // 6: jobworker.v1.JobWorker.Stop:output_type -> jobworker.v1.StopResponse
	6, // 7: jobworker.v1.JobWorker.GetStatus:output_type -> jobworker.v1.GetStatusResponse
	8, // 8: jobworker.v1.JobWorker.StreamOutput:output_type -> jobworker.v1.StreamOutputResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jobworker_v1_jobworker_proto_init() }
func file_jobworker_v1_jobworker_proto_init() {
	if File_jobworker_v1_jobworker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobworker_v1_jobworker_proto_rawDesc), len(file_jobworker_v1_jobworker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobworker_v1_jobworker_proto_goTypes,
		DependencyIndexes: file_jobworker_v1_jobworker_proto_depIdxs,
		EnumInfos:         file_jobworker_v1_jobworker_proto_enumTypes,
		MessageInfos:      file_jobworker_v1_jobworker_proto_msgTypes,
	}.Build()
	File_jobworker_v1_jobworker_proto = out.File
	file_jobworker_v1_jobworker_proto_goTypes = nil
	file_jobworker_v1_jobworker_proto_depIdxs = nil
}
